### ISSUE TITLE
Greeting

### ISSUE THREAD

**Issue by gurucutup** [colin-axner/SuperClean-code#1]
Hi  Colin.

How are you?
My name is Justin and I noticed that you are currently working on FourthState Labs and truly impressed by your work.
As a software developer it would be great if we could have a talk.
Have something to discuss and wanna build something beautiful on your chain so need your help.

Apologize for this sudden msg but hope you understand.

Let me be available.
Telegram : @idiot_pool
Discord : idiotpool#7777
Email: [justinstone0603@gmail.com](mailto:justinstone0603@gmail.com)

Best

**Comment by colin-axner** [comment]
Hi, I am not interested.
